.TH "md_CHANGELOG" 3 "Version v1.0" "xchange" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_CHANGELOG \- Changelog 
.PP
 All notable changes to the \fCSmithsonian/xchange\fP library will be documented in this file\&.
.PP
The format is based on \fCKeep a Changelog\fP, and this project adheres to \fCSemantic Versioning\fP\&.
.SH "[1\&.0\&.0-rc7] - 2025-03-20"
.PP
Release candidate for initial public release\&. 
