.TH "XLookupTable" 3 "Version v0.9" "xchange" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XLookupTable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xchange\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBpriv\fP"
.br
.RI "Private data, not exposed to users\&. "
.in -1c
.SH "Detailed Description"
.PP 
A fast lookup table for fields in large XStructures\&.
.PP
\fBSee also\fP
.RS 4
\fBxCreateLookup()\fP 
.PP
\fBxLookupField()\fP 
.PP
\fBxDestroyLookup()\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for xchange from the source code\&.
